export const projects = [
  {
    title: 'Ocean Rising',
    description: "A Virtual Reality Multiplayer underwater adventure developed in Unity. Video game was developed with Steam VR and is compatible with most VR headsets",
      image: '/images/1.gif',
      tags: ['Unity', 'C#', 'SteamVR', 'Networking', 'Github'],
    source: 'https://www.youtube.com/watch?v=tFe0lzTQAf4',
    visit: 'https://github.com/Team-Odyssey/OceanRising',
    id: 0,
  },
  {
    title: 'Gat.or',
    description:"A video synchronization application built on a SERN stack and utilizing socket.io for real-time synchronization and chat.",
    image: '/images/2.PNG',
    tags: ['React', 'SQL', 'Express', 'Node.js', 'AWS', 'APIs', 'Bootstrap'],
    source: 'https://gator.studio/',
    visit: 'https://github.com/Gat-or/webapp',
    id: 1,
  },
  {
    title: 'Fabula(b)',
    description: "Worked with the Fabula(b) theatre and new media incubator to prototype different AR prototypes and features. Source files for these projects are not available to the public.",
      image: '/images/3.gif',
      tags: ['Unity', 'C#', 'AR Foundations', 'Github'],
    source: 'https://ebhunter.wordpress.com/fabulab/',
    visit: 'https://ebhunter.wordpress.com/portfolio/miguel-mellado-sfsu-senior/',
    id: 2,
  },
  {
    title: 'Chat Application',
    description: "A  full Realtime Chat Application using React.js for the front end and Node.js with the Socket.io web socket library on the back end.",
    image: '/images/4.PNG',
    tags: ['React', 'Express', 'Node', "Socket.io", 'Heroku', 'Netlify'],
    source: 'https://miggy-chat.netlify.app/',
    visit: 'https://github.com/Miguel619/chat-app',
    id: 3,
  },
  {
    title: 'Wall Builder Prototype',
    description: "An AR Prototype application for building a wall in real space. This app includes options for changing the size and color of your brick.",
    image: '/images/5.PNG',
    tags: ['Unity', 'C#', 'AR Foundations'],
    source: 'https://github.com/Miguel619/Wall-Builder',
    visit: 'https://github.com/Miguel619/Wall-Builder',
    id: 4,
  },
  {
    title: 'Wack A Nutcracker',
    description: "An IOS AR mini-game aimed at shoot nutcrackers with a baseball. Developed exclusively for ios with Swift and AR kit",
    image: '/images/6.PNG',
    tags: ['Swift', 'SwiftUI', 'AR Kit', 'Reality Composer', 'XCode'],
    source: 'https://github.com/Miguel619/Wack-A-NutCracker',
    visit: 'https://github.com/Miguel619/Wack-A-NutCracker',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a Computer Science Student in San Diego.', },
  { year: 2019, text: 'Started my Upper Division major courses and working on side projects in San Francisco.', },
  { year: 2020, text: 'Began leading development of full stack web applications with gat.or.', },
  { year: 2021, text: 'Got hired working on Mixed Reality applications in Unity followed by a position as a Software Engineer.', },
];